---
groups:
- name: main
  jobs:
  - test
  - build-docker-image
  - job-deploy-app

jobs:

- name: test
  serial: true
  disable_manual_trigger: false
  plan:
      - get: Node-js-app
        trigger: true

      - task: npm-install
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: node, tag: "6" }
          inputs:
            - name: Node-js-app
              path: .
          run:
            path: npm
            args: [ install ]

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: Node-js-app
    trigger: true
    passed: 
      - unit-tests
  - put: docker-image
    params:
      build: Node-js-app
      
- name: job-deploy-app
  serial: true
  plan:
  - get: Node-js-app
    trigger: true
    passed: 
      - build-docker-image
  - put: cf-env
    params:
      manifest: Node-js-app/manifest.yml
      path: Node-js-app
  
resources:
- name: Node-js-app
  type: git
  source:
    uri: https://github.com/vc4017/cf-sample-app-nodejs.git
    branch: master
    
- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: vc4017@gmail.com
    password: Venki@521
    organization: vc4017-org
    space: deployment
    skip_cert_check: true
- name: docker-image
  type: docker-image
  source:
    email: tovenki.ch@gmail.com
    username: venki521
    password: venki@521
    repository: venki521/sampleapp
    
