---
resources:
- name: resource-web-app
  type: git
  source:
    uri: https://github.com/vc4017/cf-sample-app-nodejs.git

- name: resource-deploy-web-app
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: tovenki.ch@gmail.com
    password: Venki@521
    organization: concourse-node.js app
    space: deployment
    skip_cert_check: true

jobs:

- name: job-test-app
  public: true
  serial: true
  plan:
  - get: cf-sample-app-nodejs
  - get: resource-web-app
    trigger: true
  - task: web-app-tests
    file: cf-sample-app-nodejs/test/task_run_tests.yml
  - put: resource-deploy-web-app
    params:
      manifest: resource-app/manifest.yml
      path: resource-app

- name: job-deploy-app
  serial: true
  plan:
  - {get: resource-web-app, trigger: true}
  - put: resource-deploy-web-app
    params:
      manifest: resource-web-app/manifest.yml
      path: resource-web-app  
