---
jobs: 

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: concourse-app
    trigger: true
  - task: run-unit-tests
    file: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/unit-tests.yml

- name: job-deploy-app
  serial: true
  plan:
  - {get: concourse-app, trigger: true}
  - put: cf-env
    params:
      manifest: concourse-app/manifest.yml
      path: concourse-app

resources: 

- name: concourse-app
  type: git
  source: 
   uri: https://github.com/vc4017/cf-sample-app-nodejs.git
  
- name: cf-env
  type: cf
  source: 
   api: https://api.run.pivotal.io
   username: tovenki.ch@gmail.com
   password: Venki@521
   organization: concourse-node.js app
   space: deployment
   skip_cert_check: true