---
groups:
- name: main
  jobs:
  - build-docker-image
  - job-deploy-app
resources:
- name: Node-js-app
  type: git
  source:
    uri: https://github.com/vc4017/cf-sample-app-nodejs.git
    branch: master
    
- name: cf-env
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: vc4017@gmail.com
    password: Venki@521
    organization: vc4017-org
    space: deployment
    skip_cert_check: true
- name: docker-image
  type: docker-image
  source:
    email: tovenki.ch@gmail.com
    username: venki521
    password: venki@521
    repository: venki521/sampleapp
    
jobs:

- name: build-docker-image
  public: true
  serial: true
  plan:
  - get: Node-js-app
    trigger: true
  - put: docker-image
    params:
      build: Node-js-app
      
- name: job-deploy-app
  serial: true
  plan:
  - {get: Node-js-app, trigger: true}
  - put: cf-env
    params:
      manifest: Node-js-app/manifest.yml
      path: Node-js-app
